package com.example.icroqueta.BBDD.Objetos;
// Generated 04-dic-2020 19:13:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String nombre;
     private String descripcion;
     private double precioUd;
     private int stock;
     private double descuento;
     private Set lineas = new HashSet(0);
     private Set carritos = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String nombre, String descripcion, double precioUd, int stock, double descuento) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.precioUd = precioUd;
        this.stock = stock;
        this.descuento = descuento;
    }
    public Producto(String nombre, String descripcion, double precioUd, int stock, double descuento, Set lineas, Set carritos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precioUd = precioUd;
       this.stock = stock;
       this.descuento = descuento;
       this.lineas = lineas;
       this.carritos = carritos;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getPrecioUd() {
        return this.precioUd;
    }
    
    public void setPrecioUd(double precioUd) {
        this.precioUd = precioUd;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(double descuento) {
        this.descuento = descuento;
    }
    public Set getLineas() {
        return this.lineas;
    }
    
    public void setLineas(Set lineas) {
        this.lineas = lineas;
    }
    public Set getCarritos() {
        return this.carritos;
    }
    
    public void setCarritos(Set carritos) {
        this.carritos = carritos;
    }




}


